### ISSUE TITLE
The HTTP request to the remote WebDriver server for URL http://localhost:49961/session timed out after 60 seconds

### ISSUE THREAD

**Issue by AlexP11223** [AlexP11223/WebChangeNotifier#1]
It worked fine, but now I get this error:

```
[01-06-2018 17:45:45] Starting web driver
[01-06-2018 17:46:47] OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:49961/session timed out after 60 seconds. ---> System.Net.WebException: The request was aborted: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at WebChangeNotifier.Worker.get_WebDriver() in C:\Users\Alex\...\Worker.cs:line 111
   at WebChangeNotifier.Worker.LoadData(MonitoringTask task) in C:\Users\Alex\...\Worker.cs:line 146
   at WebChangeNotifier.Worker.Process(MonitoringTask task) in C:\Users\Alex\...\Worker.cs:line 184
   at WebChangeNotifier.Worker.<Run>b__22_1(MonitoringTask task) in C:\Users\Alex\...\Worker.cs:line 243
```

**Comment by AlexP11223** [comment]
Looks like it's caused by the latest Chrome WebDriver or Chrome.

For now try deleting `browser_data` folder when you encounter this.
